jaffle-shop-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth-secrets
      project: ada2025-450209
      dataset: jaffle_shop
      threads: 2
      token: your_access_token